//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cv.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCvEntities1 : DbContext
    {
        public DbCvEntities1()
            : base("name=DbCvEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TblAdmin> TblAdmin { get; set; }
        public DbSet<TblDeneyimlerim> TblDeneyimlerim { get; set; }
        public DbSet<TblEgitimlerim> TblEgitimlerim { get; set; }
        public DbSet<TblHakkimda> TblHakkimda { get; set; }
        public DbSet<TblHobilerim> TblHobilerim { get; set; }
        public DbSet<TblIletisim> TblIletisim { get; set; }
        public DbSet<TblSertifikalarim> TblSertifikalarim { get; set; }
        public DbSet<TblSosyalMedya> TblSosyalMedya { get; set; }
        public DbSet<TblYeteneklerim> TblYeteneklerim { get; set; }
    }
}
