//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cv.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSosyalMedya
    {
        public int ID { get; set; }
        public string AD { get; set; }
        public string LINK { get; set; }
        public string ICON { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
